version: "3.8"

services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file: .env
    environment:
      NODE_ENV: development
      DB_URL: ${DB_URL}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
